#!/usr/bin/env python3
import sys
import os
import subprocess
import argparse
import datetime

NOTE_DIR = os.path.expanduser('~/notes/')


def listing():
    """list all cats and notes"""
    for e in os.listdir(NOTE_DIR):
        if os.path.isdir(os.path.join(NOTE_DIR, e)):
            print(e)
            for ee in os.listdir(os.path.join(NOTE_DIR, e)):
                print("    " + ee.replace('_', ' '))


def create_note(args):
    dstr = str(datetime.date.today())
    name = dstr + "_" + "_".join(args.name)
    note_folder = os.path.join(NOTE_DIR, args.category)
    os.makedirs(note_folder, exist_ok=True)
    file_path = os.path.join(note_folder, name)

    header = dstr + " " + " ".join(args.name)

    with open(file_path, 'w') as fp:
        fp.write(header)
        fp.write('\n')
        fp.write('=' * len(header))
        fp.write('\n\n')
    cmd = 'nvim %s' % file_path
    print(cmd)
    p = subprocess.Popen(cmd.split())
    p.wait()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--category', '-c', action='store', default='unsorted')
    parser.add_argument('--list', '-l', action='store_true')
    parser.add_argument('name', nargs='*')
    args = parser.parse_args()

    if args.list:
        listing()
        sys.exit(0)

    create_note(args)


if __name__ == '__main__':
    main()
